aristokrat/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from . import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns

admin.autodiscover()

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^$', include('categories.urls')),
    url(r'^catalog', include('goods.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += staticfiles_urlpatterns()

categories/urls.py
from django.conf.urls import url

from categories.views import CategoriesList

urlpatterns = [
    url(r'^', CategoriesList.as_view(), name='categories')
]

goods/urls.py
from django.conf.urls import url

from goods.views import GoodsDetail, Search, GoodsFilterView

urlpatterns = [
    url(r'^/all', GoodsFilterView.as_view(), name='all'),
    url(r'^/(?P<id>\d+)', GoodsFilterView.as_view(), name='catalog'),
    url(r'^/goods/(?P<id>\d+)', GoodsDetail.as_view(), name='goods'),
    url(u'^/search/(?P<search>[\w\-]+)/$', Search.as_view(), name='search'),
]

references/urls.py
from django.conf.urls import url



urlpatterns = [
]

categories/models.py
import os
from django.db import models



class Categories(models.Model):
    name = models.CharField(max_length=50, verbose_name='Название',blank=True, null=True, default=None)
    menu_title = models.CharField(max_length=50, verbose_name='Текст ссылки', blank=True, null=True, default=None)

    def __str__(self):
        return "Категория %s" % self.name

    class Meta:
        verbose_name = 'Категория'
        verbose_name_plural = 'Категории'

goods/models.py
import os
from django.db import models
from django.utils.safestring import mark_safe

from categories.models import Categories
from references.models import Genres




class GoodsBase(models.Model):
    name = models.CharField(max_length=50, null=True, blank=True, default=None, verbose_name='Название')
    description = models.TextField(null=True, blank=True, default=None, verbose_name='Описание')
    price = models.IntegerField(null=True, blank=True, default=None, verbose_name='Цена')
    edition_date = models.DateTimeField(auto_now=True, blank=True, verbose_name='Дата добавления')
    public = models.BooleanField(verbose_name='Публикация')
    category = models.ForeignKey(Categories, blank=True, null=True, default=None, verbose_name='Категории')
    author = models.CharField(max_length=100, null=True, blank=True, default=None, verbose_name='Автор')
    creation_date = models.DateField(default=None, blank=True, null=True, verbose_name='Период создания')
    genre = models.ForeignKey(Genres, blank=True, null=True, default=None, verbose_name='Жанр')

class Images(models.Model):
    image = models.ImageField()
    good = models.ForeignKey(GoodsBase, blank=True, null=True, default=None)

    def url(self):
        return str(self.image.url)

    class Meta:
        verbose_name = 'Изображение'
        verbose_name_plural = 'Изображения'

# class Goods(GoodsBase):
#     def __str__(self):
#         return self.name
#
#     class Meta:
#         verbose_name = 'Товар'
#         verbose_name_plural = 'Другие товары'


# class Pictures(GoodsBase):
#     size = models.CharField(max_length=12, blank=True, null=True, default=None, verbose_name='Размер')
#
#     def __str__(self):
#         return self.name
#
#     class Meta:
#         verbose_name = 'Картина'
#         verbose_name_plural = 'Картины'


class Antiques(GoodsBase):
    def __str__(self):
        return self.name

    class Meta:
        verbose_name = 'Антиквариат'
        verbose_name_plural = 'Антиквариат'

references/models.py
import os
from django.db import models


class Genres(models.Model):
    name = models.CharField(max_length=50, blank=True, null=True, default=None, verbose_name='Стиль')

    class Meta:
        verbose_name_plural = 'Стили'
        verbose_name = 'Стиль'

    def __str__(self):
        return self.name


# class Authors(models.Model):
#     name = models.CharField(max_length=50, blank=True, null=True, default=None, verbose_name='ФИО')
#
#     class Meta:
#         verbose_name_plural = 'Авторы'
#         verbose_name = 'Автор'
#
#     def __str__(self):
#         return self.name

categories/forms.py
from django import forms
from .models import *

class GoodForm(forms.ModelForm):
    preifx = 'comment_form'
    class Meta:
        model = Goods
        labels = {
            "name": "Имя",
            "text": "Комментарий",
        }
        exclude = [""]

goods/forms.py
from django import forms
from .models import *

class GoodForm(forms.ModelForm):
    preifx = 'comment_form'
    class Meta:
        model = Goods
        labels = {
            "name": "Имя",
            "text": "Комментарий",
        }
        exclude = [""]

categories/views.py
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import ListView, DetailView

from .models import *


class CategoriesList(ListView):
    model = Categories

    context_object_name = 'categories'
    template_name = 'base.html'
    paginate_by = 30

    def get_queryset(self):
        qs = Categories.objects.all()
        return qs

goods/views.py
from django.db.models import Q
from django.shortcuts import render, render_to_response
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views.generic import ListView, DetailView
from django_filters.views import FilterView

from goods.filters import GoodsFilter
from .models import *


class CategoryGoodsList(ListView):
    model = GoodsBase

    context_object_name = 'goods'
    template_name = 'goods.html'
    paginate_by = 30

    def get_queryset(self):
        qs = GoodsBase.objects.filter(category__in=self.kwargs['id'], public=True).order_by('-edition_date')
        return qs

class AllCategoriesList(ListView):
    model = GoodsBase

    context_object_name = 'goods'
    template_name = 'goods.html'
    paginate_by = 30

    def get_queryset(self):
        qs = GoodsBase.objects.filter(public=True).order_by('-edition_date')
        return qs

class GoodsFilterView(FilterView):
    model = GoodsBase
    filterset_class = GoodsFilter
    template_name = 'goods.html'

    def get_filterset_kwargs(self, filterset_class):
        filter_kwargs = super(GoodsFilterView, self).get_filterset_kwargs(filterset_class)
        if filter_kwargs["data"] is None:
            filter_kwargs["data"] = {"category": self.kwargs.get('id')}
        return filter_kwargs


    def get_context_data(self, **kwargs):
        context = super(GoodsFilterView, self).get_context_data(**kwargs)
        context['categories'] = Categories.objects.all()
        return context


class GoodsDetail(DetailView):
    model = GoodsBase

    context_object_name = 'good'
    template_name = 'detail_goods.html'
    pk_url_kwarg = 'id'

    def get_context_data(self, **kwargs):
        context = super(GoodsDetail, self).get_context_data(**kwargs)
        context['related'] = GoodsBase.objects.all().order_by('-id')[:3]
        context['categories'] = Categories.objects.all()
        return context


class Search(ListView):
    model = GoodsBase

    context_object_name = 'goods'
    template_name = 'goods.html'
    paginate_by = 30

    def get_queryset(self):
        search = self.kwargs['search']
        qs = GoodsBase.objects.filter(Q(name__contains=search) | Q(description__contains=search), public=True).order_by('-edition_date')
        return qs

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% load static %}
    {% include "bootstrap.html" %}
</head>
<body>
{% include "header.html" %}
<div class="container">
    <div class="row">

        <img class="flower" src="{% static '/assets/flower.png' %}">

        <div class="col-md-2 col-xs-12 category-menu-wrapper">
            <nav>
                <ul>
                    {% include "category_menu.html" %}
                </ul>
            </nav>
        </div>
    </div>
</div>
{% include "footer.html" %}
</body>
</html>

templates/bootstrap.html
<meta name="viewport" content="width=device-width, initial-scale=1">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
{% load static %}
<link rel="stylesheet" href="{% static '/css/main.css' %}">
<link rel="stylesheet" href="{% static '/css/lightslider.css' %}">
<script src="{% static 'js/lightslider.js/' %}"></script>
<script src="{% static '/js/main.js' %}"></script>
<link href="http://allfont.ru/allfont.css?fonts=baskerville-bold-it-win95bt" rel="stylesheet" type="text/css" />
<link href="http://allfont.ru/allfont.css?fonts=baskerville-bold-win95bt" rel="stylesheet" type="text/css" />
<link href="http://allfont.ru/allfont.css?fonts=baskerville-win95bt" rel="stylesheet" type="text/css" />
<script src="https://cdnjs.cloudflare.com/ajax/libs/lightslider/1.1.6/js/lightslider.min.js" integrity="sha256-nHmCK+HOPMPezzS3ky9VKznMWH4sW4keT8HrMaDNbYo=" crossorigin="anonymous"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/lightslider/1.1.6/css/lightslider.min.css" integrity="sha256-ev+XS9lVA6/6vEe/p9pncQjsHB6g9UtAZYFLNViXxAA=" crossorigin="anonymous" />

templates/category_menu.html
<!DOCTYPE html>
{% load static %}
<img class="krendel" src="{% static '/assets/krendel.png' %}">
<li class="nav-title"><a class="nav-item" href="{% url 'all' %}">Все категории</a></li>
{% for i in categories %}
    <li>
        <a class="nav-item" href="{% url 'catalog' i.id %}">{{ i.name }}</a>
    </li>
{% endfor %}

templates/detail_goods.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% include "bootstrap.html" %}
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.css" />
    <script src="https://cdnjs.cloudflare.com/ajax/libs/ekko-lightbox/5.3.0/ekko-lightbox.js"></script>
</head>
<body>
<div class="container-fluid">
    {% include "header.html" %}
    <div class="container mobile-body" >
        <div class="row" style="margin-top: 30px">
            <div class="col-md-5 gallery">
                <div class="mainimage center-block">
                    <ul id="imageGallery">
                        {% for image in good.images_set.all %}
                            <li data-thumb="{{ image.url }}" data-src="{{ image.url }}">
                                <img class="gallery" src="{{ image.url }}" />
                            </li>
                        {% endfor %}
                    </ul>
                </div>
            </div>
            <div class="col-md-6 good-data">
                <div class="row name">
                    <h1 style="margin-top: 0px!important;">{{ good.name }}</h1>
                </div>
                <div class="row">
                    <label class="detail-label">Дата добавления: </label>{{ good.edition_date|date:"d.m.y" }}
                </div>
                <div class="row">
                    {% if good.creation_date %}
                        <label class="detail-label">Период создания: </label>{{ good.creation_date|date:"d.m.y" }}
                    {% endif %}
                </div>
                <div class="row">
                    {% if good.author %}
                        <label class="detail-label">Автор: </label>{{ good.author }}
                    {% endif %}
                </div>
                <div class="row">
                    {% if good.genre %}
                        <label class="detail-label">Жанр: </label>{{ good.genre }}
                    {% endif %}
                </div>
                <div class="row">
                    {% if good.size %}
                        {{ good.size }}
                    {% endif %}
                </div>

                <div class="price-detail" style="  font-size: 32px;
    position: relative;
    bottom: 0;
    right: 0;
    margin-top: 35%;
    text-align: right;
    font-family: 'Baskerville Bold Win95BT', arial">
                    <p>{{ good.price }} руб.</p>
                </div>

            </div>
        </div>
        <div class="row">
            <div class="col-md-5 description">
                <p>{{ good.description }}</p>
            </div>
        </div>
        <div class="recomend">
            <p style="margin-bottom: 10px; font-family: 'Baskerville-bold;">Рекомендуем посмотреть:</p>
            <ul class="related col-md-8">
                {% for item in related %}
                    <li class="related-item col-md-4">
                        <div class="related-image-holder row">
                            <a href="{% url 'goods' item.pk %}">
                                <img class="related-images col-md-12" src="{{ item.images_set.all.0.url }}">
                            </a>
                        </div>
                        {#                            <div class="related-link row">#}
                        {#                                {{ item.name }}#}
                        {#                            </div>#}
                    </li>
                {% endfor %}
            </ul>
        </div>
    </div>


    {% include "footer.html" %}
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $('#imageGallery').lightSlider({
            gallery:true,
            item:1,
            loop:true,
            thumbItem:2,
            slideMargin:0,
            enableDrag: false,
            currentPagerPosition:'left',
            onSliderLoad: function(el) {
                el.lightGallery({
                    selector: '#imageGallery .lslide'
                });
            }
        });
    });
</script>
</body>
</html>

templates/footer.html
<footer>
    <div class="row">
        <p class="contacts">г. Владимир, ул. Горького, д. 75, тел. 8 904 507 89 43, e-mail: aristokrat@yandex.ru</p>
    </div>
</footer>

templates/goods.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    {% include "bootstrap.html" %}
</head>
<body>
<div class="container-fluid">
    {% include "header.html" %}

    {% block content %}
        <div class="container">
            <div class="row">
                <div class="col-md-4 ">
                    {#            <ul class="goods-filter">#}
                    {#                <li class="filter-top">#}
                    {#                    <p>Дата добавления</p>#}
                    {#                </li>#}
                    {#                <li>#}
                    {#                    <p>Период создания</p>#}
                    {#                </li>#}
                    {#                <li>#}
                    {#                    <p>Жанр</p>#}
                    {#                </li>#}
                    {#                <li>#}
                    {#                    <p>Цена</p>#}
                    {#                </li>#}
                    {#            </ul>#}
{#                    <button data-toggle="collapse" data-target="#collapse-filter">Фильтр</button>#}
                    <form class="goods-filter" id="collapse-filter" action="" method="get">
                        {{ filter.form.as_p }}

                        <button class="btn-default filter-button" name="name" value="value" type="submit">Выбрать</button>

                    </form>
                    {#                {% for obj in filter.qs %}#}
                    {#                    {{ obj.name }} - ${{ obj.price }}<br />#}
                    {#                {% endfor %}#}


                </div>
                <div class="col-md-8 goods">
                    <div class="row text-center">

                        {% for i in filter.qs %}
                            <a class="good" href="{% url 'goods' i.id %}">
                                <div class="col-md-4 blockgoods">
                                    <div class="blockgoods-content">
                                        <img src="{{ i.images_set.all.0.url }}">
                                        <h1>{{ i.name }}</h1>
                                        <p>{{ i.price }} руб.</p>
                                    </div>
                                </div>
                            </a>
                        {% endfor %}

                    </div>
                    <!--
            <ul class="goods-list">
                {% for i in filter.qs %}
                    <li class="categories-list">
                        <div class="col-md-12">
                            <div class="row">
                                <div class="category-image-wrapper">
                                    <img class="category-preview col-md-12" src="{{ i.images_set.all.0.url }}">
                                </div>
                            </div>
                            <div class="row">
                                <div class="description">
                                    <a class="goods-title" href="{% url 'goods' i.id %}">{{ i.name }}</a><br/>
                                    <p class="price">
                                        {{ i.price }} руб.
                                    </p>
                                </div>
                            </div>
                        </div>
                    </li>
                {% endfor %}
            </ul>

            -->
                </div>
            </div>
        </div>
    {% endblock %}

    {% include "footer.html" %}
</div>
</body>
</html>

templates/goods/goodsbase_filter.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

templates/header.html
{% load static %}
<header>
   <div class="container">
    <div class="row">
        <nav class="navbar navbar-default">
            <div class="container-fluid">
                <div class="navbar-header">
                    <div class="col-md-4 text-left">
                        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                            <span class="icon-bar"></span>
                        </button>
                        <a class="logo" href="{% url 'categories' %}"><img class="logo-image logo" src="{% static '/assets/logo.png' %}"></a>
                    </div>
                    {#                    <div class="col-md-1 hidden-xs-up col-xs-offset-0 col-md-offset-1">#}
                    {#                        <a class="contacts-header" href="#">Контакты</a>#}
                    {#                    </div>#}
                    <div class="col-md-4 col-md-offset-2 col-xs-12 search-wrapper text-right">
                        <div class="inner-addon right-addon">
                            <a id="search-btn" class="glyph-s glyphicon glyphicon-search"></a>
                            <input placeholder="Поиск" class="search form-control" type="text" id="search"/>
                        </div>
                    </div>
                    <div class="col-md-2 col-xs-12 text-left phone-mobile">
                        <p class="phone-header">8 904 257 07 25</p>
                    </div>
                </div>
                <div class="collapse navbar-collapse" id="myNavbar">
                    <ul class="nav navbar-nav">
                        {% include "category_menu.html" %}
                    </ul>
                </div>
            </div>
        </nav>
    </div>
       </div>
</header>